version: '3.8'

services:
  # Aplicação ASP.NET Core Mercado Bonsai (.NET 10)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mercadobonsai_web
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
